### ISSUE TITLE
Investigate Fiber prefork

### ISSUE THREAD

**Issue by codemicro** [riceteacatpanda/sinensis-api#1]
Using `app.Settings.Prefork = true` can increase the speed of a Fiber application, especially when being used in production on a multithreaded server. It does this by creating multiple processes **that do not share memory space** which requires some design changes.

More info [here](https://www.nginx.com/blog/socket-sharding-nginx-release-1-9-1/).

Items that need addressing:
* Email sending
* Incorrect sign-in attempts
* Ratelimiting
* CAPTCHA for sign-ups
* Automatic GeoIP downloads
* Settings

**Comment by codemicro** [comment]
## Email sending
**At most, I'd like only two emails to be being sent at one time.** In its current state, this is achieved using one channel and two goroutines running the same function. 
```go
var (
    sendQueue  = make(chan Message, 1024*1024)
)

func mailWorker() {
    for {
        toSend := <-sendQueue
        toSend.Send()
        time.Sleep(time.Millisecond * 100)
	}
}

func InitEmail() error {
    // ...
    go mailWorker()
    go mailWorker()
    // ...
}
```
This is dependent on a single process. Once we end up running multiple processes, this approach will no longer work as there will be **`n * 2` `mailWorker` instances running**, where `n` is the number of processes created by enabling prefork.

### Possible solutions
Fiber provides an interface to determine if the currently running process is a child process or a parent process. There will only ever be one parent process. 
```go
if !app.IsChild() {
    go mailWorker()
    go mailWorker()
}
```
However, this means that the channel approach cannot be used because the memory space is not shared. This means that an in-memory data store will have to be used. There are a couple of options for this:
* Redis
* [KeyDB](https://keydb.dev/) - a faster fork of Redis that maintains full compatability with Redis APIs
* Use the standard DB (which is not in-memory, but that can be ignored)
  * There's no easy way to ensure that only one worker is accessing the database and reserving a task for themselves at once.
  * Doing so will require an extra mutex to prevent the same email being sent more than once.

Another potential solution still uses Redis, but uses a completely external worker program. This will increase configuration and setup complexity, and it most likely excessive when it can be done inside the main app.

**Comment by codemicro** [comment]
## Incorrect sign-in attempts
Incorrect sign-in attempts are tracked against a user's IP address in a `map[string]int` in memory. This would not persist across multiple processes and hence multiple memory spaces.

### Potential solutions
* Redis/KeyDB as proposed previously
* Standard DB
  * Potentially slower than the Redis/KeyDB option.
  * Will also increase load on the SQL database, which I'd like to avoid as much as possible.

**Comment by codemicro** [comment]
## Ratelimiting
Ratelimiting is currently done with the [gofiber/limiter](https://github.com/gofiber/limiter) middleware which uses **in-memory** tracking against IP addresses. Again, memory spaces and processes, yada yada yada.

### Potential solutions
* Third party limiter middleware with Redis integration ([Shareed2k/fiber_limiter](https://github.com/Shareed2k/fiber_limiter))
  * Ease of use is unknown - requires more research
* Writing a custom middleware
  * Will require backing by Redis/KeyDB.
  * Using the main SQL DB is **not an option** due to the huge load this would create.

**Comment by codemicro** [comment]
## CAPTCHA for sign-ups
The plan was to use [dchest/captcha](https://github.com/dchest/captcha) to do generate and manage CAPTCHAs, which uses an in memory data store to store CAPTCHA IDs.

Anything we're going to do will involve some Redis/KeyDB implementation. There's not really any point storing this in the standard SQL database.

### Potential solutions
* Fork and modify [dchest/captcha](https://github.com/dchest/captcha)
  * Fairly substantial codebase, looks time consuming/annoying to modify.
* Find another CAPTCHA library with Redis support
* DIY the CAPTCHA stuff
  * May well require a significant amount of time, but it'll be fun. Right??

**Comment by codemicro** [comment]
## CAPTCHA for sign-ups
The plan was to use [dchest/captcha](https://github.com/dchest/captcha) to do generate and manage CAPTCHAs, which uses an in memory data store to store CAPTCHA IDs.

Anything we're going to do will involve some Redis/KeyDB implementation. There's not really any point storing this in the standard SQL database.

### Potential solutions
* Fork and modify [dchest/captcha](https://github.com/dchest/captcha)
  * Fairly substantial codebase, looks time consuming/annoying to modify.
* Find another CAPTCHA library with Redis support
* DIY the CAPTCHA stuff
  * May well require a significant amount of time, but it'll be fun. Right??

**Comment by vihanb** [comment]
Another potential solution is to go ReCaptcha, just sayin :P

**Comment by codemicro** [comment]
## Automatic GeoIP downloads
I was planning to integrate automatic GeoIP database downloads using Maxmind licence keys. If each process is going to be loading the database individually, it doesn't seem like there's going to be any easy way to inform each process that they need to reload the database. 

### Potential solutions
* Do away with automatic downloads and make it entirely manual
* Allow automatic downloads but they require an API restart to take effect (is there any way to orchestrate this from within the API?)
* Script that's run from the command line that downloads databases that way

**Comment by codemicro** [comment]
## Settings
The initial plan for settings was to have a disk-backed key-value datastore that would have settings directly written to/from it. For this, I was using [peterbourgon/diskv](https://github.com/peterbourgon/diskv) but that's got an in-memory cache **that has no option to set a TTL value** (see [peterbourgon/diskv#23](https://github.com/peterbourgon/diskv/issues/23)).

### Potential solutions
* Fork and modify DiskV
* Implement a new key-value store from scratch
* Use the SQL database
  * Creating a simple key-value system there would just be a case of making a new table with two columns
* Redis/KeyDB with persistence

**Comment by codemicro** [comment]
As of [`ac74605`](https://github.com/riceteacatpanda/sinensis-api/commit/ac746053bff92d18e1993647c327125e4d7f9daa), everything should have been addressed and the app should be able to run nicely in prefork mode!
